source 'https://rubygems.org'

gem 'activerecord-import'
gem 'activerecord-session_store'
gem 'acts_as_list', github: 'swanandp/acts_as_list'
gem 'acts-as-taggable-on'
gem 'audited-activerecord'
gem 'axlsx'
gem 'axlsx_rails'
gem 'bluecloth'
gem 'bootstrap-sass'
gem 'bootstrap-select-rails'
gem 'bootstrap3-datetimepicker-rails'
gem 'capistrano'
gem 'capistrano-ext'
gem 'coffee-rails'
gem 'country_select'
gem 'delayed_job_active_record'
gem 'devise', '~> 3.5.1'
gem 'dynamic_form'
gem 'execjs'
gem 'exception_notification'
gem 'filterrific'
gem 'grape', '0.7.0'
gem 'grape-entity', '~> 0.4.4'
gem 'grouped_validations', :git => 'https://github.com/jleonardw9/grouped_validations.git', branch: 'master'
gem 'gyoku'
gem 'haml'
gem 'icalendar'
gem 'inflection-js-rails'
gem 'jquery_datepicker'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'json'
gem 'letter_opener'
gem 'momentjs-rails', '>= 2.8.1'
gem 'mysql2', '~> 0.3.18'
gem 'nested_form'
gem 'nested_form_fields'
gem 'newrelic_rpm'
gem 'nokogiri'
gem 'nori'
gem 'nprogress-rails'
gem 'obis-net-ldap'
gem 'omniauth'
gem 'omniauth-shibboleth'
gem 'paperclip', '~> 3.4.1'
gem 'pdfkit'
gem 'prawn', '0.12.0'
gem 'premailer-rails'
gem 'protected_attributes'
gem 'rails', '4.2.4'
gem 'rails-html-sanitizer'
gem 'redcarpet'
gem 'remotipart'
gem 'rest-client'
gem 'rvm-capistrano', require: false
gem 'sass'
gem 'sass-rails'
gem 'savon', '~> 2.2.0'
gem 'simplecov', require: false, group: :test
gem 'sinatra'
gem 'surveyor', :git => 'https://github.com/sparc-request/surveyor.git', branch: 'rails4'
gem 'therubyracer', '0.10.2', :platforms => :ruby
gem 'twitter-typeahead-rails'
gem 'uglifier', '>= 1.0.3'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'x-editable-rails'

group :development, :test, :profile do
  gem 'addressable', '~> 2.3.6'
  gem 'bullet'
  gem 'connection_pool'
  gem 'equivalent-xml'
  gem 'faker'
  gem 'launchy'
  gem 'thin'
  gem 'timecop'
  gem 'progress_bar'
end

group :development, :test do
  gem 'pry'
  gem 'rails-erd'
  gem 'rspec-rails', '~> 3.3.3'
end

group :development do
  gem 'highline'
  gem 'spring-commands-rspec'
  gem 'spring'
  gem 'sqlite3'
  gem 'traceroute'
  gem 'parallel_tests', group: :development
end

group :test do
  gem 'capybara-webkit'
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'factory_girl_rails'
  gem 'rspec-activemodel-mocks'
  gem 'rspec-html-matchers'
  gem 'shoulda-matchers', require: false
  gem 'shoulda-callback-matchers'
  gem 'site_prism'
  gem 'webmock'
end

group :profile do
  gem 'ruby-prof'
end
