# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73d0359754179b216986c23eebb0ce89e9def98737176cbb607d1a4e92f6be5cd6594a88d3783f3685d7f9bf7b964081bef0a0a9a0d32e802f80052bf318c55f

test:
  secret_key_base: 8aedbf799de5165d8b3dc0cfe850678fa2774edaa2945c3939f506478f9c0961634ad8d52325328bf16ccaa3ae86c0677dc1d410d9bce4ee1fe5b46fa643383c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
